+----------+------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Query_ID | Duration   | Query                                                                                                                                                                                                                      |
+----------+------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|        4 | 0.02651752 | SELECT p.*, s.* FROM PARTITIONS AS p INNER JOIN SDS AS s, TBLS AS t, DBS AS d WHERE p.SD_ID = s.SD_ID AND p.TBL_ID = t.TBL_ID AND t.DB_ID = d.DB_ID AND d.NAME = 'tpch_partitioned_orc_4' AND t.TBL_NAME = 'orders'   |
|        5 | 0.03322264 | SELECT p.*, s.* FROM PARTITIONS AS p INNER JOIN SDS AS s, TBLS AS t, DBS AS d WHERE p.SD_ID = s.SD_ID AND p.TBL_ID = t.TBL_ID AND t.DB_ID = d.DB_ID AND d.NAME = 'tpch_partitioned_orc_4' AND t.TBL_NAME = 'orders'   |
|        6 | 0.04169284 | SELECT p.*, s.* FROM PARTITIONS AS p INNER JOIN SDS AS s, TBLS AS t, DBS AS d WHERE p.SD_ID = s.SD_ID AND p.TBL_ID = t.TBL_ID AND t.DB_ID = d.DB_ID AND d.NAME = 'tpch_partitioned_orc_4' AND t.TBL_NAME = 'orders'   |
|        7 | 0.03758360 | SELECT p.*, s.* FROM PARTITIONS AS p INNER JOIN SDS AS s, TBLS AS t, DBS AS d WHERE p.SD_ID = s.SD_ID AND p.TBL_ID = t.TBL_ID AND t.DB_ID = d.DB_ID AND d.NAME = 'tpch_partitioned_orc_4' AND t.TBL_NAME = 'orders'   |
|        8 | 0.03972703 | SELECT p.*, s.* FROM PARTITIONS AS p INNER JOIN SDS AS s, TBLS AS t, DBS AS d WHERE p.SD_ID = s.SD_ID AND p.TBL_ID = t.TBL_ID AND t.DB_ID = d.DB_ID AND d.NAME = 'tpch_partitioned_orc_4' AND t.TBL_NAME = 'orders'   |
|        9 | 0.04197274 | SELECT p.*, s.* FROM PARTITIONS AS p INNER JOIN SDS AS s, TBLS AS t, DBS AS d WHERE p.SD_ID = s.SD_ID AND p.TBL_ID = t.TBL_ID AND t.DB_ID = d.DB_ID AND d.NAME = 'tpch_partitioned_orc_4' AND t.TBL_NAME = 'orders'   |
|       10 | 0.03621543 | SELECT p.*, s.* FROM PARTITIONS AS p INNER JOIN SDS AS s, TBLS AS t, DBS AS d WHERE p.SD_ID = s.SD_ID AND p.TBL_ID = t.TBL_ID AND t.DB_ID = d.DB_ID AND d.NAME = 'tpch_partitioned_orc_4' AND t.TBL_NAME = 'lineitem' |
|       11 | 0.03860857 | SELECT p.*, s.* FROM PARTITIONS AS p INNER JOIN SDS AS s, TBLS AS t, DBS AS d WHERE p.SD_ID = s.SD_ID AND p.TBL_ID = t.TBL_ID AND t.DB_ID = d.DB_ID AND d.NAME = 'tpch_partitioned_orc_4' AND t.TBL_NAME = 'lineitem' |
|       12 | 0.01991747 | SELECT p.*, s.* FROM PARTITIONS AS p INNER JOIN SDS AS s, TBLS AS t, DBS AS d WHERE p.SD_ID = s.SD_ID AND p.TBL_ID = t.TBL_ID AND t.DB_ID = d.DB_ID AND d.NAME = 'tpch_partitioned_orc_4' AND t.TBL_NAME = 'lineitem' |
|       13 | 0.03209231 | SELECT p.*, s.* FROM PARTITIONS AS p INNER JOIN SDS AS s, TBLS AS t, DBS AS d WHERE p.SD_ID = s.SD_ID AND p.TBL_ID = t.TBL_ID AND t.DB_ID = d.DB_ID AND d.NAME = 'tpch_partitioned_orc_4' AND t.TBL_NAME = 'lineitem' |
|       14 | 0.02400280 | SELECT p.*, s.* FROM PARTITIONS AS p INNER JOIN SDS AS s, TBLS AS t, DBS AS d WHERE p.SD_ID = s.SD_ID AND p.TBL_ID = t.TBL_ID AND t.DB_ID = d.DB_ID AND d.NAME = 'tpch_partitioned_orc_4' AND t.TBL_NAME = 'lineitem' |
|       15 | 0.03397861 | SELECT p.*, s.* FROM PARTITIONS AS p INNER JOIN SDS AS s, TBLS AS t, DBS AS d WHERE p.SD_ID = s.SD_ID AND p.TBL_ID = t.TBL_ID AND t.DB_ID = d.DB_ID AND d.NAME = 'tpch_partitioned_orc_4' AND t.TBL_NAME = 'lineitem' |
|       16 | 0.04258564 | SELECT p.*, s.* FROM PARTITIONS AS p INNER JOIN SDS AS s, TBLS AS t, DBS AS d WHERE p.SD_ID = s.SD_ID AND p.TBL_ID = t.TBL_ID AND t.DB_ID = d.DB_ID AND d.NAME = 'tpch_partitioned_orc_4' AND t.TBL_NAME = 'lineitem' |
|       17 | 0.04010650 | SELECT p.*, s.* FROM PARTITIONS AS p INNER JOIN SDS AS s, TBLS AS t, DBS AS d WHERE p.SD_ID = s.SD_ID AND p.TBL_ID = t.TBL_ID AND t.DB_ID = d.DB_ID AND d.NAME = 'tpch_partitioned_orc_4' AND t.TBL_NAME = 'lineitem' |
|       18 | 0.03579120 | SELECT p.*, s.* FROM PARTITIONS AS p INNER JOIN SDS AS s, TBLS AS t, DBS AS d WHERE p.SD_ID = s.SD_ID AND p.TBL_ID = t.TBL_ID AND t.DB_ID = d.DB_ID AND d.NAME = 'tpch_partitioned_orc_4' AND t.TBL_NAME = 'lineitem' |
|       19 | 0.04678154 | SELECT p.*, s.* FROM PARTITIONS AS p INNER JOIN SDS AS s, TBLS AS t, DBS AS d WHERE p.SD_ID = s.SD_ID AND p.TBL_ID = t.TBL_ID AND t.DB_ID = d.DB_ID  AND d.NAME = 'tpch_partitioned_orc_4' AND t.TBL_NAME = 'orders'   |
|       20 | 0.04367708 | SELECT p.*, s.* FROM PARTITIONS AS p INNER JOIN SDS AS s, TBLS AS t, DBS AS d WHERE p.SD_ID = s.SD_ID AND p.TBL_ID = t.TBL_ID AND t.DB_ID = d.DB_ID  AND d.NAME = 'tpch_partitioned_orc_4' AND t.TBL_NAME = 'orders'   |
|       21 | 0.03819219 | SELECT p.*, s.* FROM PARTITIONS AS p INNER JOIN SDS AS s, TBLS AS t, DBS AS d WHERE p.SD_ID = s.SD_ID AND p.TBL_ID = t.TBL_ID AND t.DB_ID = d.DB_ID  AND d.NAME = 'tpch_partitioned_orc_4' AND t.TBL_NAME = 'orders'   |
+----------+------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+


